name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Clean
      run: dotnet clean src/WA/SoleMatesWA/SoleMatesWA.csproj

    - name: Restore dependencies
      run: dotnet restore src/WA/SoleMatesWA/SoleMatesWA.csproj

    - name: Build
      run: dotnet build src/WA/SoleMatesWA/SoleMatesWA.csproj

    - name: Test
      run: dotnet test src/WA/SoleMatesWA/SoleMatesWA.csproj --no-build

    - name: Publish
      run: |
        dotnet publish src/WA/SoleMatesWA/SoleMatesWA.csproj --configuration Release --output ./publish

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish